FROM alpine:3.14
LABEL version="1.0"
LABEL maintainer="team@zaion.ai"

# Install python/pip
ENV PYTHONUNBUFFERED=1
RUN apk add --update --no-cache python3 && ln -sf python3 /usr/bin/python
RUN python3 -m ensurepip
RUN pip3 install --no-cache --upgrade pip setuptools
RUN apk add nano
RUN apk add sqlite-dev

RUN echo "setup WORKDIR..."
RUN mkdir /usr/local/agassist
WORKDIR /usr/local/agassist

COPY . /usr/local/agassist


# Log message for installing Python dependencies
RUN echo "Installing Python dependencies..."
COPY setup/requirements.txt /usr/local/agassist/requirements.txt
RUN pip3 install -r /usr/local/agassist/requirements.txt

RUN echo "Copying main.py and config files..."
#COPY bin/main.py /usr/local/agassist/bin/main.py
#COPY config /usr/local/agassist/config

RUN echo "Creating logs directory..."
RUN mkdir /usr/local/agassist/logs


# Clean up unnecessary files
RUN rm -r -f /var/cache/apk/*

RUN echo "Setting up FastAPI server..."
EXPOSE 9000

# Command to run the FastAPI server
CMD ["uvicorn", "bin.main:app", "--host", "0.0.0.0", "--port", "9000"]
